// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuvqVtHwBookYuF4T_z02AzTg2y8Qyry0',
    appId: '1:1046826949997:web:f584d0adad49a83a370e64',
    messagingSenderId: '1046826949997',
    projectId: 'chatapp-317f2',
    authDomain: 'chatapp-317f2.firebaseapp.com',
    storageBucket: 'chatapp-317f2.firebasestorage.app',
    measurementId: 'G-R32VM5RCSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSfFux7UyFWGcKx7IV1zJfqfS8xMUOzLU',
    appId: '1:1046826949997:android:0ca3b7cf791a5056370e64',
    messagingSenderId: '1046826949997',
    projectId: 'chatapp-317f2',
    storageBucket: 'chatapp-317f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZqw_zbQpvLnX8_TpR2eNCKj4wvANWRX0',
    appId: '1:1046826949997:ios:67ec819146e84f89370e64',
    messagingSenderId: '1046826949997',
    projectId: 'chatapp-317f2',
    storageBucket: 'chatapp-317f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZqw_zbQpvLnX8_TpR2eNCKj4wvANWRX0',
    appId: '1:1046826949997:ios:67ec819146e84f89370e64',
    messagingSenderId: '1046826949997',
    projectId: 'chatapp-317f2',
    storageBucket: 'chatapp-317f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuvqVtHwBookYuF4T_z02AzTg2y8Qyry0',
    appId: '1:1046826949997:web:8911ca8df6b06533370e64',
    messagingSenderId: '1046826949997',
    projectId: 'chatapp-317f2',
    authDomain: 'chatapp-317f2.firebaseapp.com',
    storageBucket: 'chatapp-317f2.firebasestorage.app',
    measurementId: 'G-2DQBMS8DPX',
  );
}
